map_type: costmap

obstacle_range: 0.7
raytrace_range: 1.0

transform_tolerance: 1.2

robot_radius: 0.15
inflation_radius: 2.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
